#lang sicp

(#%require "12.rkt")
(#%require "10.rkt")

(define a1 (make-center-percent 100 1))
(define b1 (make-center-percent 78 0.5))
(define a2 (make-center-percent 320 1))
(define b2 (make-center-percent 178 4))
(define a3 (make-center-percent 120 0.1))
(define b3 (make-center-percent 278 0.5))
(define a4 (make-center-percent 100 5))
(define b4 (make-center-percent 78 2))

(define (div-report a b)
  (let ((c (div-interval a b)))
	  (display (center a))
	  (display " ")
	  (display (percent a))
	  (display " / ")
	  (display (center b))
	  (display " ")
	  (display (percent b))
	  (display " = ")
	  (display (center c))
	  (display " ")
	  (display (percent c))
	  (newline)))

(div-report a1 a1)
(div-report a1 b1)
(div-report a2 a2)
(div-report a2 b2)
(div-report a3 a3)
(div-report a3 b3)
(div-report a4 a4)
(div-report a4 b4)
